config/routes.rb
Liveinapp::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :apps do 
    resources :comments
    resources :rates
    resources :news
    member do
      post :using
      post :comment
    end
    
  end
  
  resources :news
  
  resources :nodes do
    resources :apps
  end

  devise_for :users, :path => 'account', :controllers => {:registrations => 'account'} do
    get '/dashboard' => 'account#index'
    get '/users/edit_avatar' => 'account#edit_avatar'
    get '/users/edit_password' => 'account#edit_password'
  end
  resources :users do
    resources :apps do
      get 'used', :on => :collection
    end
  end
  root :to => 'home#index'

  match ':id' => "pages#show", :as => :page
  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/node.rb
class Node < ActiveRecord::Base
  # has_many :nodes, :class_name => 'Node', :foreign_key => 'parent_id', :dependent => :destroy
  # belongs_to :parent, :class_name => 'Node', :foreign_key => 'parent_id'
  # acts_as_tree :order => "sort"
  has_many :apps
  
  scope :hots, order("apps_count desc")
  
  # def all_apps
    # if self.leaf?
      # self.apps
    # else
      # App.where(:node_id => self.childless)
    # end
  # end
#   
  def self.hot_node_collection
    Node.hots.collect { |n| [n.name,n.id] }
  end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  layout 'three_column', :only => :show
  # GET /nodes
  # GET /nodes.json
  def index
    @nodes = Node.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @nodes }
    end
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
    @node = Node.find(params[:id])
    @apps = @node.apps.approved.page params[:page]
    
  end

  # GET /nodes/new
  # GET /nodes/new.json
  def new
    @node = Node.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @node }
    end
  end

  # GET /nodes/1/edit
  def edit
    @node = Node.find(params[:id])
  end

  # POST /nodes
  # POST /nodes.json
  def create
    @node = Node.new(params[:node])

    respond_to do |format|
      if @node.save
        format.html { redirect_to root_path }
      else
        format.html { render action: "new" }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /nodes/1
  # PUT /nodes/1.json
  def update
    @node = Node.find(params[:id])

    respond_to do |format|
      if @node.update_attributes(params[:node])
        format.html { redirect_to @node, notice: 'Node was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    @node = Node.find(params[:id])
    @node.destroy

    respond_to do |format|
      format.html { redirect_to nodes_url }
      format.json { head :ok }
    end
  end
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/nodes/_form.html.erb
<%= simple_form_for(@node, :html => { :class => "form-horizontal" }) do |f| %>
  <%= f.input :name %>
  <%= f.input :summary %>
  <%= f.input :sort %>
  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/nodes/edit.html.erb
<h1>Editing node</h1>

<%= render 'form' %>

<%= link_to 'Show', @node %> |
<%= link_to 'Back', nodes_path %>

app/views/nodes/index.html.erb
<h1>Listing nodes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Summary</th>
    <th>Sort</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @nodes.each do |node| %>
  <tr>
    <td><%= node.name %></td>
    <td><%= node.summary %></td>
    <td><%= node.sort %></td>
    <td><%= link_to 'Show', node %></td>
    <td><%= link_to 'Edit', edit_node_path(node) %></td>
    <td><%= link_to 'Destroy', node, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Node', new_node_path %>

app/views/nodes/new.html.erb
<h1>New node</h1>

<%= render 'form' %>

<%= link_to 'Back', nodes_path %>

app/views/nodes/show.html.erb
<h2><%= @node.name %></h2>
<div class="apps">
  <% @apps.each do |app| %>
    <% if app.logo? %>
    <%= link_to(image_tag(app.logo_url(:thumb)), app)%>
    <% else %>
      <%= link_to app.name, app%>
    <% end %>
  <% end %>
<%= paginate @apps %>
</div>
<% content_for :sidebar do%>
  <%= render :partial => "common/add_node_link" %>
<% end %>