config/routes.rb
Liveinapp::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :apps do 
    resources :comments
    resources :rates
    resources :news
    member do
      post :using
      post :comment
    end
    
  end
  
  resources :news
  
  resources :nodes do
    resources :apps
  end

  devise_for :users, :path => 'account', :controllers => {:registrations => 'account'} do
    get '/dashboard' => 'account#index'
    get '/users/edit_avatar' => 'account#edit_avatar'
    get '/users/edit_password' => 'account#edit_password'
  end
  resources :users do
    resources :apps do
      get 'used', :on => :collection
    end
  end
  root :to => 'home#index'

  match ':id' => "pages#show", :as => :page
  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/views/apps/_form.html.erb
<div id="app-tab" class="tabbable">
  <ul class="nav nav-tabs">
    <li class="active">
      <a href="#basic" data-toggle="tab">云应用基本信息</a>
    </li>
    <li>
      <a href="#pricing" data-toggle="tab">云应用价格表</a>
    </li>
  </ul>
  <%= simple_form_for(@app, :html => { :class => "form-horizontal" }) do |f| %>
  <div class="tab-content">
    <div class="tab-pane active" id="basic">
      <%= f.input :name do %>
      <%= f.collection_select :node_id, Node.all, :id, :name%>
      <%= f.text_field :name, :class => "span3"%>
      <% end %>
      <%= f.input :url, :placeholder => "http://", :input_html => { :class => 'input-xlarge' }%>
      <%= f.input :logo do %>
      <%= f.hidden_field :logo_cache %>
      <div class="row">
        <div class="span4">
          <%= f.file_field :logo, :class => 'span3'%>
        </div>
        <div class="span12">
          <%= image_tag(@app.logo_url(:thumb)) if @app.logo?%>
        </div>
      </div>
      <% end %>
      <%= f.input :desc, :as => :text, :input_html => {:rows=>6, :class => 'span6'}, :placeholder => "支持markdown格式" %>
      </fieldset>
    </div>
    <div class="tab-pane" id="pricing">
      <%= f.input :trial, :wrapper => :append, :hint => "不填表示完全免费、填0表示没有免费试用" do %>
      <%= f.input_field :trial, :class => "input-mini" %>
      <%= content_tag :span, "天", :class => "add-on" %>
      <% end %>
      <%= f.input :pricing_url, :placeholder => "http://", :input_html => { :class => 'input-xlarge' }%>
      <%= f.input :pricing, :as => :text, :input_html => {:rows=>6, :class => 'span6'}, :placeholder => "支持markdown格式"  %>
      </fieldset>
    </div>
  </div>
  <div class="form-actions">
    <%= f.button :submit, t("common.save"), :class => "btn-primary", :disable_with => t("common.saving")%>
    <%= link_to t("common.cancel"), @app.id.blank? ? root_path : app_path(@app), :class => "btn"%>
  </div>
  <% end %>
</div>

app/views/apps/edit.html.erb
<div class="box">
<%= render 'form' %>
</div>

app/views/apps/index.html.erb
<% content_for :title do %><%=@node.present? ? @node.name : "所有云服务"%> - <%= Settings.app_name%><% end %>
<div class="box">
  <h2><%= apps_menu(params) %></h2>
  <div id="apps">
    <%= render :partial => "common/app", :collection => @apps %>
    <%= paginate @apps, :theme => 'bootstrap' %>
  </div>
</div>
<% content_for :sidebar do%>
<div class="box">
  <%= render :partial => "common/add_node_link" %>
</div>
<div class="box">
  <%= render :partial => "common/summary"%>
</div>
<div class="box box-break">
  <h2>谁在用</h2>
  <ul class="unstyled appusings">
    <% @appusings.each do |using|%>
      <li>
        <span><i class=" icon-user"></i><%= link_to using.user.name, user_path(using.user.name)%>正在用<%= link_to using.app.name, app_path(using.app)%></span>
      </li>
    <% end %>
  </ul>
</div>
<% end %> 

app/views/apps/new.html.erb
<div class="box">
  <%= render 'form' %>
</div>

app/views/apps/show.html.erb
<% content_for :title do %><%=@app.name%> - <%= Settings.app_name%><% end %>
<div class="span12">
  <div class="box app-wrap">
    <div class="apps">
      <div class="app-item" id="app-<%= @app.id%>">
      <div class="row-fluid">
        <div class="app-main">
          <div class="row-fluid app-basic">
            <div class="span8">
              <%= link_to(image_tag(@app.logo_url(:thumb)), @app, :class => "app-logo box")%>
              <div>
                <p class="app-title">
                  <%= link_to content_tag(:strong, @app.name), app_path(@app)%>
                  <%= link_to("编辑", edit_app_path(@app)) if @app.created_by(current_user)%>
                </p>
                <p>
                  <a href="<%= @app.url %>" target="_blank"><i class='icon-home'></i><%= @app.url %></a>
                </p>
                <p>
                  <a href="<%= user_path(@app.user.name) %>"><i class='icon-user'></i><%= @app.user.name %></a>
                </p>
                <p>
                  <a href="<%= node_apps_path(@app.node) %>"><i class='icon-tag'></i><%= @app.node_name %></a>
                </p>
              </div>
             </div>
            <div class="span4">
              <div class="row-fluid">
                <div class="app-star span7">
                  <%= raw render_stars(@app)%>
                  <div>
                    <span class="app-star-title">&nbsp;</span>(<a href="#"><%=@app.rater_count%>人评价</a>)
                  </div>
                </div>
                <div class="span5 my-star">
                  <% if current_user.nil? || !current_user.using?(@app) %>
                      <%= link_to "用过", "#star-modal", :class => "btn btn-inverse", 'data-toggle' => "modal"%>
                  <% else %>
                    <span class="label label-info">我用过这个应用</span>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <div class="row-fluid app-desc">
            <%= raw(@app.desc_html) %>
          </div>
        </div>
      </div>
      <div class="row-fluid app-bar">
        <div class="span12">
          <div class="pull-right">
            <a href="<%= app_path(@app) %>#app-users"><i class="icon-ok-sign"></i><%= @app.rater_count %>人使用</a>
            <a href="<%= app_path(@app) %>#comments"><i class='icon-comment'></i>评论(<%= @app.comments_count%>)</a>
          </div>
        </div>
      </div>
    </div>
    </div>
  </div>
  <div class="row">
    <div class="span12">
      <div class="box">
        <h2>
          套餐价格
          <div class="pull-right">
            <a href="<%= @app.pricing_url%>" target="_blank"><i class="icon-eye-open"></i>官方链接</a>
          </div>
        </h2>
        <div>
        	<%= raw @app.pricing_html %>
        </div>
      </div>
    </div>
    <div class="span8">
      <div id="comments" class="box">
        <h2>评论，共<strong><%= @app.comments_count%></strong>条评论</h2>
        <ul class="unstyled">
          <%= render :partial => "comments/comment", :collection => @comments, :locals => {:app => @app }%>
          <li>
            <% if current_user.present? %>
            <%= form_for Comment.new, :remote => true, :url => app_comments_path(@app) do |f| %>
              <%= f.text_area :body, :rows=>4, :style => "width: 500px;" %>
              <%= f.submit "提交评论", :class => "btn-primary", :disable_with => t("common.saving")%>
            <% end %>
            <% else %>
              <p>
                需要 <%= link_to('登录', new_user_session_path, :class => "btn btn-primary")  %> 才能评论，如果没有帐号请先 <%= link_to('注册', new_user_registration_path, :class => "btn btn-inverse")  %>
              </p>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
    <div class="span4">
      <%= render_cell :news, :sidebar_app_latest_news, :app => @app %>
      <div class="box" id="app-users">
        <h2>有<strong><%= @app.rater_count%></strong>人使用该应用</h2>
        <ul class="thumbnails">
        	<% @users.each do |user|%>
        		<li>
        			<%= user_avatar_tag(user, :small) %>
        			<p><%= link_to user.name, user_path(user.name) %></p>
        		</li>
        	<% end %>
        </ul>
      </div>
      <div class="box">
        <h2>同类应用</h2>
        <ul class="thumbnails">
          <% @other_apps.each do |app|%>
            <li>
              <%= link_to(image_tag(app.logo_url(:thumb)), app, :title => app.url)%><br />
            </li>
          <% end %>
        </ul>
        <div class="row-fluid"><%= link_to "更多应用(#{@app.node.apps_count})", node_apps_path(@app.node), :class => "pull-right"%></div>
      </div>
    </div>
  </div>
</div>
<div class="modal" id="star-modal" style="display: none;">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    <h3>评价</h3>
  </div>
  <div class="modal-body">
    <%= simple_form_for Rate.new, :url => app_rates_path(@app) do |f|%>
      <%= f.input :user_status, :label => false do %>
        <div class="row-fluid">
          <div class="span2">
          <%= f.label :user_status, :class => "radio inline", :style=>"margin-left:0;" do %>
            <%= f.radio_button :user_status, "0", :checked => 'checked' %>用过
          <% end %>
          </div>
          <div class="app-star span10">
            <%= raw render_stars(@app, true)%>
          </div>
        </div>
      <% end %>
      <%= f.input :body, :input_html => {:rows=>3, :class => 'span7'} %>
    <% end %>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal">关闭</a>
    <a href="#" class="btn btn-primary" onclick="javascript: forms['new_rate'].submit();">保存</a>
  </div>
</div>
<%= content_for :scripts do %>
  <script type="text/javascript">
    $(function() {
      $("#star-modal").on('show', function() {
        
      })
    })
  </script>
  
<% end %>

app/views/apps/user_index.html.erb
<div class="box">
  <h2><%= @user.name %><%= params[:action] == 'index' ? '提交' : '正在使用'%>的应用</h2>
  <div id="apps">
    <%= render :partial => "common/app", :collection => @apps %>
    <%= paginate @apps, :theme => 'bootstrap' %>
  </div>
</div>