config/routes.rb
Liveinapp::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :apps do 
    resources :comments
    resources :rates
    resources :news
    member do
      post :using
      post :comment
    end
    
  end
  
  resources :news
  
  resources :nodes do
    resources :apps
  end

  devise_for :users, :path => 'account', :controllers => {:registrations => 'account'} do
    get '/dashboard' => 'account#index'
    get '/users/edit_avatar' => 'account#edit_avatar'
    get '/users/edit_password' => 'account#edit_password'
  end
  resources :users do
    resources :apps do
      get 'used', :on => :collection
    end
  end
  root :to => 'home#index'

  match ':id' => "pages#show", :as => :page
  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/views/common/_add_node_link.html.erb
<p style="text-align: center;">
  <%= link_to "提交应用", @node.nil? ? new_app_path : new_node_app_path(@node), :class => "btn btn-success"%>
</p>

app/views/common/_app.html.erb
<div class="app-item" id="app-<%= app.id%>">
  <div class="row-fluid">
    <div class="app-main">
      <div class="row-fluid app-basic">
        <%= link_to(image_tag(app.logo_url(:thumb)), app, :class => "app-logo box")%>
        <div>
          <p class="app-title">
            <%= link_to content_tag(:strong, app.name), app_path(app)%>
          </p>
          <p>
            <a href="<%= app.url %>" target="_blank"><i class='icon-home'></i><%= app.url %></a>
          </p>
          <p>
            <a href="<%= user_path(app.user.name) %>"><i class='icon-user'></i><%= app.user.name %></a>
          </p>
          <p>
            <a href="<%= node_apps_path(app.node) %>"><i class='icon-tag'></i><%= app.node_name %></a>
          </p>
        </div>
      </div>
      <div class="row-fluid app-desc">
        <%= truncate(app.desc, :length => 80) %>
      </div>
    </div>
  </div>
  <div class="row-fluid app-bar">
    <div class="span12">
      <div class="pull-right">
        <a href="<%= app_path(app) %>#app-users"><i class="icon-ok-sign"></i><%= app.rater_count %>人使用</a>
        <a href="<%= app_path(app) %>#comments"><i class='icon-comment'></i>评论(<%= app.comments_count%>)</a>
      </div>
    </div>
  </div>
</div>

app/views/common/_feed.html.erb
<li>
  <div class="row-fluid">
    <div class="span1">
      <%= user_avatar_tag(feed.user, :small)%>
    </div>
    <div class="feed-content">
      <p>
        <%= link_to feed.user.name, user_path(feed.user.name)%>
        <% case feed.target_type %>
        <% when 'Comment' %>
        对<%= link_to feed.data['target_title'], app_path(feed.data['target_id'])%>应用发表评论
        <% when 'Rate' %>
        用过<%= link_to feed.data['target_title'], app_path(feed.data['target_id'])%>
        <% when 'App' %>
        <%= feed.action=='ADD' ? '提交了' : '修改了' %><%= link_to feed.data['target_title'], app_path(feed.data['target_id'])%>应用
        <% end %>
        <%= timeago(feed.created_at, icon='')%>
      </p>
      <% if feed.data['body'].present? %>
      <p class="feed-body">
        <%= feed.data['body'] %>
      </p>
      <% end %>
    </div>
  </div>
</li>

app/views/common/_nodes.html.erb
<ul class="unstyled">
  <% Node.all.each do |node|%>
    <li><%= link_to "#{node.name}(#{node.apps_count.present? ? node.apps_count : 0})", node_apps_path(node) %></li>
  <% end %>
</ul>

app/views/common/_summary.html.erb
<h2><%= @node.nil? ? "网站介绍" : @node.name%></h2>
<p>
  <%= @node.nil? ? Settings.app_summary : @node.summary %>
</p>