config/routes.rb
Liveinapp::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :apps do 
    resources :comments
    resources :rates
    resources :news
    member do
      post :using
      post :comment
    end
    
  end
  
  resources :news
  
  resources :nodes do
    resources :apps
  end

  devise_for :users, :path => 'account', :controllers => {:registrations => 'account'} do
    get '/dashboard' => 'account#index'
    get '/users/edit_avatar' => 'account#edit_avatar'
    get '/users/edit_password' => 'account#edit_password'
  end
  resources :users do
    resources :apps do
      get 'used', :on => :collection
    end
  end
  root :to => 'home#index'

  match ':id' => "pages#show", :as => :page
  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= content_for?(:title) ? yield(:title) : "Obeycloud.com - 发现云服务，推荐云服务，分享与交流云使用心得" %></title>
		<meta name="keywords" content="云主机 云笔记 云存储 数据云 云监控 云笔记 分享 交流" />
    <meta name="description" content="obeycloud.com提供了发现、分享、推荐云服务的一个平台" />
		<%= stylesheet_link_tag "application", params[:controller]%>
		<%= yield :styles %>
		<%= javascript_include_tag "application", params[:controller] %>
		<%= yield :scripts %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<div class="navbar">
			<div class="navbar-inner">
				<div class="container">
					<a class="brand" href="/"><%= Settings.app_name %></a>
					<%= tabs_tag :open_tabs => {:class => "nav"} do |tab| %>
            <%= tab.home '首页', root_path %>
            <%= tab.apps  '云应用', apps_path %>
            <%= tab.news '新闻', news_index_path %>
          <% end %>
					<form class="navbar-search pull-left" action="">
						<input type="text" class="search-query span3" placeholder="搜索云应用">
					</form>
					<ul class="nav pull-right" id="userbar">
						<% if user_signed_in? %>
						<li>
							<%= link_to("我的主页", user_path(current_user.name)) %>
						</li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown"> <%= current_user.name%><b class="caret"></b> </a>
							<ul class="dropdown-menu">
								<li>
									<%= link_to("修改资料", edit_user_registration_path)%>
								</li>
								<li>
									<%= link_to('退出', destroy_user_session_path, :method => :delete) %>
								</li>
							</ul>
						</li>
						<% else %>
						<li>
							<%= link_to('注册', new_user_registration_path)  %>
						</li>
						<li>
							<%= link_to('登录', new_user_session_path)  %>
						</li>
						<% end %> <li class="divider-vertical"></li>
						<li>
							<%= link_to content_tag(:span, "提交应用", :class=>"label label-success"), @node.nil? ? new_app_path : new_node_app_path(@node)%>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<div class="container">
			<%= notice_message %>
			<div class="row">
				<%= content_for?(:content) ? yield(:content) : yield %>
			</div>
			<footer>
			  <p>
			    <% cache("page_links") do %>
			      <% @pages = Page.all; pages_len = @pages.size%>
  			    <% @pages.each_with_index do |page, index| %>
  			    <%= link_to page.title, page_path(page.slug) %><%= "|" if index != pages_len-1%>
  			    <% end %>
			    <% end %>
			  </p>
				<p>
					<%= raw Settings.foot_html %>
				</p>
			</footer>
		</div>
	</body>
</html>

app/views/layouts/three_column.html.erb
<% content_for :content do %>
  <div class="span2">
    <div class="box">
    <%= render_cell :app, :sidebar_app_nodes %>
    </div>
    <%= render_cell :global, :stats %>
  </div>
  <div class="span7">
    <%= yield %>
  </div>
  <div class="span3">
    <%= yield :sidebar%>
  </div>
<% end %>
<%= render :template => "layouts/application"%>

app/views/layouts/two_column.html.erb
<% content_for :content do %>
  <div class="span9">
    <%= yield %>
  </div>
  <div class="span3">
    <%= yield :sidebar%>
  </div>
<% end %>
<%= render :template => "layouts/application"%>

app/views/layouts/user.html.erb
<% content_for :content do %>
  <div class="span3">
    <div class="box">
      <div class="row-fluid owner">
        <div class="span4">
          <%= user_avatar_tag(@user, :large)%>
        </div>
        <div class="span8">
          <p class="user-name"><%= link_to(content_tag(:strong, @user.name), user_path(@user.name))%></p>
          <%if current_user.present? && current_user.id==@user.id%>
            <p><%= link_to("修改资料", edit_user_registration_path)%></p>
          <% else %>
            <p><%= link_to("关注此人", "#")%></p>
          <% end %>
        </div>
      </div>
    </div>
    <%= yield :sidebar %>
  </div>
  <div class="span9">
    <%= yield %>
  </div>
<% end %>
<%= render :template => "layouts/application"%>